### ISSUE TITLE
向cluster监听的端口，发送特定数据，会导致进程崩溃

### ISSUE THREAD

**Issue by jxianglonggg** [cloudwu/skynet#1481]
我们测试环境的机器没有开防火墙，一直有公网上的ip来连skynet进程监听的cluster端口，并发送数据，导致崩溃。
崩溃后的堆栈
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./server/Game_H5MJ_3 config'.
Program terminated with signal 11, Segmentation fault.
#0  lunpackrequest (L=0x7fdd1978ac08) at lualib-src/lua-cluster.c:369
369             switch (msg[0]) {
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64 libgcc-4.8.5-16.el7_4.1.x86_64
(gdb) bt
#0  lunpackrequest (L=0x7fdd1978ac08) at lualib-src/lua-cluster.c:369
#1  0x0000000000415a58 in luaD_precall (L=L@entry=0x7fdd1978ac08, func=func@entry=0x7fdd197879c0, nresults=-1) at ldo.c:503
#2  0x00000000004231c6 in luaV_execute (L=L@entry=0x7fdd1978ac08, ci=<optimized out>) at lvm.c:1617
#3  0x0000000000415b80 in ccall (L=0x7fdd1978ac08, func=<optimized out>, nResults=<optimized out>, inc=65537) at ldo.c:548
#4  0x0000000000414ec5 in luaD_rawrunprotected (L=L@entry=0x7fdd1978ac08, f=f@entry=0x4112e0 <f_call>, ud=ud@entry=0x7fdd209e0280) at ldo.c:147
#5  0x0000000000415f52 in luaD_pcall (L=L@entry=0x7fdd1978ac08, func=func@entry=0x4112e0 <f_call>, u=u@entry=0x7fdd209e0280, old_top=192, ef=<optimized out>) at ldo.c:784
#6  0x0000000000412b0e in lua_pcallk (L=L@entry=0x7fdd1978ac08, nargs=<optimized out>, nresults=nresults@entry=-1, errfunc=errfunc@entry=0, ctx=ctx@entry=0, 
    k=k@entry=0x42cef0 <finishpcall>) at lapi.c:1033
#7  0x000000000042cf95 in luaB_pcall (L=0x7fdd1978ac08) at lbaselib.c:455
#8  0x0000000000415a58 in luaD_precall (L=L@entry=0x7fdd1978ac08, func=func@entry=0x7fdd197878a0, nresults=2) at ldo.c:503
#9  0x00000000004231c6 in luaV_execute (L=L@entry=0x7fdd1978ac08, ci=<optimized out>) at lvm.c:1617
#10 0x0000000000415b80 in ccall (L=0x7fdd1978ac08, func=<optimized out>, nResults=<optimized out>, inc=65537) at ldo.c:548
#11 0x0000000000414ec5 in luaD_rawrunprotected (L=L@entry=0x7fdd1978ac08, f=f@entry=0x4112e0 <f_call>, ud=ud@entry=0x7fdd209e0570) at ldo.c:147
#12 0x0000000000415f52 in luaD_pcall (L=L@entry=0x7fdd1978ac08, func=func@entry=0x4112e0 <f_call>, u=u@entry=0x7fdd209e0570, old_top=48, ef=<optimized out>) at ldo.c:784
#13 0x0000000000412b0e in lua_pcallk (L=L@entry=0x7fdd1978ac08, nargs=nargs@entry=5, nresults=nresults@entry=0, errfunc=errfunc@entry=1, ctx=ctx@entry=0, k=k@entry=0x0) at lapi.c:1033
#14 0x00007fdd197ba5a8 in _cb (context=0x7fdd1967e980, ud=0x7fdd1978ac08, type=3, session=25, source=83, msg=0x0, sz=0) at lualib-src/lua-skynet.c:75
#15 0x0000000000409c6f in dispatch_message (ctx=ctx@entry=0x7fdd1967e980, msg=msg@entry=0x7fdd209e0650) at skynet-src/skynet_server.c:274
#16 0x000000000040a7cc in skynet_context_message_dispatch (sm=sm@entry=0x7fdd2ca093a0, q=0x7fdd174f8ec0, weight=weight@entry=2) at skynet-src/skynet_server.c:334
#17 0x000000000040af6e in thread_worker (p=<optimized out>) at skynet-src/skynet_start.c:163
#18 0x00007fdd2dbbbe25 in start_thread () from /lib64/libpthread.so.0
#19 0x00007fdd2cfc534d in clone () from /lib64/libc.so.6
(gdb) f 0
#0  lunpackrequest (L=0x7fdd1978ac08) at lualib-src/lua-cluster.c:369
369             switch (msg[0]) {
(gdb) p msg
$1 = 0x0
```
重现步骤:
1.skynet 进程启用cluster监听端口
2.使用下面的代码去连接并发送数据
```
local crypt  = require "crypt"
local socket = require "lsocket"
local fd = socket.connect(host, cluster端口)
print(fd)
local package = string.char(0) .. string.char(0)
print("package =", crypt.hexencode(package))
socket.send(fd, package)
```
这个问题，改下防火墙，能解决，但是是不是skynet要做好判断，收到异常数据，可以在lua层出错，而不是崩溃。

**Comment by cloudwu** [comment]
该问题等价于：如何识别(判断)连接是否是合法的。但这必须有严格的密码学上的握手协议才可以保证没有恶意攻击。这个实现成本和运行维护成本都远远超过了加一个防火墙。而且这本身也是防火墙的职责范畴。

**Comment by SheepQi** [comment]
我觉得他的意思应该是跟判定玩家链接一样，如果数据不合法直接丢掉包并断开连接，而不是crash掉

**Comment by cloudwu** [comment]
cluster 的内部协议是用于进程内部，是会传递进程内指针的，这样才能避免数据拷贝。玩家协议是跨机器跨进程，所有数据都是序列化过的。

只要用传递指针的方式通讯，就不可能判断。

**Comment by cloudwu** [comment]
除了设定防火墙，推荐的方式是组个 vpn 将所有节点机器放进去。cluster 只监听 vpn 的地址。这也是 Virtual Private Network 原本的应用场合。

**Comment by jxianglonggg** [comment]
谢谢解惑。我之前在用防火墙和对这种情况特判抛lua异常来处理之间犹豫。

**Comment by cloudwu** [comment]
@jxianglonggg 我又看了一下，这里的崩溃不是解析指针引起的，的确应该多加一个判断比较好。已经提交了修改。

**Comment by jxianglonggg** [comment]
> @jxianglonggg 我又看了一下，这里的崩溃不是解析指针引起的，的确应该多加一个判断比较好。已经提交了修改。

好的。

**Comment by ylme** [comment]
不过服务器可对公网开放的端口应该只是 login 端口这种吧，其余端口只能在主机局域网内访问，这应该是基本的方针。
