### ISSUE TITLE
lua-datasheet.c崩溃问题

### ISSUE THREAD

**Issue by lf723** [cloudwu/skynet#721]
```c
Program terminated with signal 11, Segmentation fault.
#0  copytable (L=0x7f52e1357a48) at lualib-src/lua-datasheet.c:239
239		const uint32_t * v = (const uint32_t *)((const char *)t + sizeof(uint32_t) + sizeof(uint32_t) + ((t->array + t->dict + 3) & ~3));
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6.x86_64 glibc-2.12-1.209.el6_9.1.x86_64
(gdb) where
#0  copytable (L=0x7f52e1357a48) at lualib-src/lua-datasheet.c:239
#1  copyfromdata (L=0x7f52e1357a48) at lualib-src/lua-datasheet.c:275
#2  0x00007f52d9673ed9 in lindex (L=0x7f52e1357a48) at lualib-src/lua-datasheet.c:282
#3  0x00000000004145e3 in luaD_precall (L=0x7f52e1357a48, func=0x7f52e14209e0, nresults=1) at ldo.c:434
#4  0x000000000041485f in luaD_call (L=0x7f52e1357a48, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:498
#5  0x000000000041d8b1 in luaT_callTM (L=0x7f52e1357a48, f=<value optimized out>, p1=<value optimized out>, p2=<value optimized out>, p3=0x7f52e1420990, hasres=1)
    at ltm.c:114
#6  0x000000000042064e in luaV_execute (L=0x7f52e1357a48) at lvm.c:896
```

```lua
datasheet.query("entity_flag")
```

不是必现，今天发现的测试服务器上的一个core dump

**Comment by hongling0** [comment]
调用builder.new那个服务不能退出

**Comment by cloudwu** [comment]
实际的数据是在调用 builder.new 的那个服务 lua vm 中，以字符串保存的。

**Comment by cloudwu** [comment]
建议实现一个用于加载原始数据的服务，由它来调用 builder 。这个服务不要退出。通常这样的服务会负责加载外部文件（或数据库），使用这个服务时传递给它文件名或索引的 key 。

**Comment by lf723** [comment]
明白，感谢
