### ISSUE TITLE
debug_console服务，http请求报错。

### ISSUE THREAD

**Issue by hanyu363** [cloudwu/skynet#926]
我用node.js. request模块请求。skynet debug_console服务时，报错。在命令行curl请求没事。
Error: Parse Error
    at Socket.socketOnData (_http_client.js:441:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
  bytesParsed: 0,
  code: 'HPE_INVALID_CONSTANT'

**Comment by cloudwu** [comment]
自己加 log 看看回应包。

**Comment by hanyu363** [comment]
我看了一下。。debug_console.的http的返回报文。不是标准的。。所以才出现问题。

**Comment by cloudwu** [comment]
回应没有 http 头，你可以认为它是  HTTP 0.9 标准。这个用法是供命令行调试用的。

**Comment by cloudwu** [comment]
建议自己额外写一个 http 协议支持服务，如果不想写，可以考虑在 https://github.com/cloudwu/skynet/blob/master/service/debug_console.lua#L104 这里改进。

**Comment by hanyu363** [comment]
已经。在改写这部分代码了。。加入了ret报文。谢谢
